// Code generated by go-swagger; DO NOT EDIT.

package flag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CountFlagsHandlerFunc turns a function with the right signature into a count flags handler
type CountFlagsHandlerFunc func(CountFlagsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CountFlagsHandlerFunc) Handle(params CountFlagsParams) middleware.Responder {
	return fn(params)
}

// CountFlagsHandler interface for that can handle valid count flags params
type CountFlagsHandler interface {
	Handle(CountFlagsParams) middleware.Responder
}

// NewCountFlags creates a new http.Handler for the count flags operation
func NewCountFlags(ctx *middleware.Context, handler CountFlagsHandler) *CountFlags {
	return &CountFlags{Context: ctx, Handler: handler}
}

/*
	CountFlags swagger:route GET /flags/count flag countFlags

CountFlags count flags API
*/
type CountFlags struct {
	Context *middleware.Context
	Handler CountFlagsHandler
}

func (o *CountFlags) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewCountFlagsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
