// Code generated by go-swagger; DO NOT EDIT.

package flag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/openflagr/flagr/swagger_gen/models"
)

// PutFullFlagOKCode is the HTTP code returned for type PutFullFlagOK
const PutFullFlagOKCode int = 200

/*
PutFullFlagOK returns the updated flag

swagger:response putFullFlagOK
*/
type PutFullFlagOK struct {

	/*
	  In: Body
	*/
	Payload *models.Flag `json:"body,omitempty"`
}

// NewPutFullFlagOK creates PutFullFlagOK with default headers values
func NewPutFullFlagOK() *PutFullFlagOK {

	return &PutFullFlagOK{}
}

// WithPayload adds the payload to the put full flag o k response
func (o *PutFullFlagOK) WithPayload(payload *models.Flag) *PutFullFlagOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put full flag o k response
func (o *PutFullFlagOK) SetPayload(payload *models.Flag) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutFullFlagOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
PutFullFlagDefault generic error response

swagger:response putFullFlagDefault
*/
type PutFullFlagDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPutFullFlagDefault creates PutFullFlagDefault with default headers values
func NewPutFullFlagDefault(code int) *PutFullFlagDefault {
	if code <= 0 {
		code = 500
	}

	return &PutFullFlagDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the put full flag default response
func (o *PutFullFlagDefault) WithStatusCode(code int) *PutFullFlagDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the put full flag default response
func (o *PutFullFlagDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the put full flag default response
func (o *PutFullFlagDefault) WithPayload(payload *models.Error) *PutFullFlagDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put full flag default response
func (o *PutFullFlagDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutFullFlagDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
